In [3]:
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]
# come struttura dati è un array

In [4]:
mat

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [10]:
import numpy as np
import math
import pandas as pd

In [7]:
mat_array = np.array(mat)

In [8]:
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
# ispezioniamo la dimensione, primo valore sempre le righe, secondo sempre colonne
mat_array.shape

(3, 5)

In [13]:
mat_array[0,:]

array([0, 1, 2, 3, 4])

In [14]:
# accedere alle ultime 2 righe
mat_array[-2,:]

array([5, 6, 7, 8, 9])

In [15]:
# questo per accedere ai singoli elementi
mat_array[1,2]

7

In [16]:
df = pd.DataFrame(mat)

In [18]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [19]:
x = math.sin(15)

In [20]:
x

0.6502878401571168

In [21]:
y = math.cos(17)

In [22]:
y

-0.27516333805159693

In [23]:
z = math.factorial(18)

In [24]:
z

6402373705728000

In [26]:
s = math.pi

In [27]:
s

3.141592653589793

In [28]:
math.degrees(math.pi)

180.0

In [29]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [30]:
lst = np.array(lst)

In [31]:
lst

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [34]:
# qual è stata la vendita massima mensile? E quella minima?
lst.max()

8150

In [35]:
lst.min()

1280

In [48]:
filter = lst[lst > 4999] # estrae i valori che soddisfano la parentesi quadra

In [49]:
filter

array([5500, 7200, 6410, 8150, 7100, 5350])

In [42]:
len(filter)

6

In [47]:
# quali sono le vendite minori di 3000 oggetti?
filter_min = lst [lst < 3000]

In [44]:
filter

array([2000, 1280, 1900, 2500])

In [50]:
len(filter_min)

4

In [55]:
# in media quanti oggetti sono stati venduti al mese?
round(lst.mean(),2)

4634.17

In [62]:
# Dunque qual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

In [57]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [63]:
#struttura dati base di Python
type(fatturati_dict[1997]) 

int

In [64]:
# con le Series si posso fare delle operazioni. E' un organizazzione dei dati per poter ispezionati interrogati e gestiti
type(fatturati_series[1997])

numpy.int64

In [66]:
# ad esempio in questo caso restrituisce il massimo tra i volari
fatturati_series.max()

25000

In [71]:
# restituisce come valore booleano i vaolri compresi nel range che stiamo ispezionando
fatturati_series[fatturati_series.between(12_000,21_000)]

1997    12000
1998    15000
1999    20000
2002    17000
2003    14000
2004    21000
dtype: int64

In [72]:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

In [75]:
# Raddoppoare stipendi con un ciclo for
lista_stipendi = []
for stipendio in stipendi:
    lista_stipendi.append(stipendio*2)
    print(lista_stipendi)

[200]
[200, 400]
[200, 400, 600]
[200, 400, 600, 800]
[200, 400, 600, 800, 1000]
[200, 400, 600, 800, 1000, 1200]
[200, 400, 600, 800, 1000, 1200, 1400]
[200, 400, 600, 800, 1000, 1200, 1400, 1600]
[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800]
[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [76]:
lista_stipendi_raddoppiati_numpy = stipendi*2

In [77]:
lista_stipendi_raddoppiati_numpy

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [80]:
for x in range (0, 100, 10):
    print(x)

0
10
20
30
40
50
60
70
80
90
